apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceService
metadata:
  name: distributed-tracing-llama
  namespace: distributed-tracing
  annotations:
spec:
  tracing:
    exporterEndpoint: "http://otel-collector:4317"
    sampler: "parentbased_traceidratio"
    samplerArg: "0.05"
    exporter: "otlp"
  router:
    scheduler:
    route: {}
    gateway:
      refs: # Reference the gateway we created
      - name: distributed-tracing-gateway
        namespace: distributed-tracing
  model:
    uri: hf://Qwen/Qwen2.5-7B-Instruct
    name: Qwen/Qwen2.5-7B-Instruct
  template:
    containers:
      - name: main
        # image: quay.io/aipcc/rhaiis/cuda-ubi9:3.4.0-ea.2 # If using Accelerators, use the corresponding inference-image, current latest RHAIIS
        #image: registry.redhat.io/rhaii-early-access/vllm-cuda-rhel9:3.4.0-ea.2-1774939203 # Official RHAIIS EA2 image
        image: registry.redhat.io/rhaii-early-access/vllm-cuda-rhel9:3.5.0-ea.1-1780065492
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '4'
            memory: 32Gi
            nvidia.com/gpu: 1
          requests:
            cpu: '2'
            memory: 16Gi
            nvidia.com/gpu: 1
        # startupProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #     scheme: HTTPS
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #     scheme: HTTPS
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #     scheme: HTTPS
